# Generated by Django 2.2 on 2020-04-20 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_code', models.PositiveSmallIntegerField(default=0)),
                ('char_code', models.CharField(default='', max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nominal', models.PositiveSmallIntegerField()),
                ('name', models.CharField(default='', max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
