version: '3'

services:
   db:
      image: postgres
      environment:
        - POSTGRES_DB=maadmin
        - POSTGRES_USER=maadmin
        - POSTGRES_PASSWORD=mapass
   app:
      build: .
      environment: 
        - DB_URL=postgres://maadmin:mapass@db/maadmin
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      depends_on:
        - db
